qhull: fix broken compatibility variant
% port info qhull +perf
Error: qhull: Error executing perf: invalid command name "ui_warning"

Also use the de facto standard form for such variants; no need to warn the
user as the migration happens automatically.