nodejs6: use bundled openssl
This is a preparation step for OpenSSL 1.1 migration. Node.js 6 does not
build with OpenSSL 1.1:

:info:build ../src/node_crypto.h:91:40: error: invalid application of 'sizeof' to an incomplete type 'SSL_CTX' (aka 'ssl_ctx_st')

I switched to bundled openssl instead of using the openssl10 port to
lower the maintenance burden. nodejs6 is EOL'ed upstream and will be
considered to be dropped once nodejs8 works on OS X 10.6, anyway.

Closes: https://trac.macports.org/ticket/58224