fontforge: update to 20200314
The previous port, 20190801_2, was broken when built with Python:

% fontforge
dyld: Symbol not found: _PyBool_Type
  Referenced from: /opt/local/lib/libfontforge.3.dylib
  Expected in: flat namespace
 in /opt/local/lib/libfontforge.3.dylib
zsh: abort      fontforge

Since 20190801, FontForge abandoned its autotools-based build in favor
of CMake. The new CMake-based build does not share this problem.