gimp2-devel: additional 10.6 build fix
On 10.6 and earlier when GDK_WINDOWING_X11 and PLATFORM_OSX
are defined simultaneously (e.g. +x11), there is
potential for a typedef conflict between X11 and Quickdraw.
In the case where this occurs, #undef PLATFORM_OSX if
GDK_WINDOWING_X11 is defined.

In otherwords, if building for X11 use the X11 API exclusively
even if we are building on OSX.

error: typedef redefinition with different types ('struct Cursor' vs 'XID' (aka 'unsigned long'))

See: https://trac.macports.org/ticket/57334