mp4v2: Revert to 4.1.3
Revert to version 4.1.3 plus patches to fix issues that were fixed in
later versions.

4.1.4 changed the signature of the MP4Read function to have a second
argument and used a C++ default value feature in doing so, thus breaking
all the ports that want to use this library from C code. Those other
ports either fail to build or fail to detect that mp4v2 is installed and
build themselves without mp4v2 support.

Closes: https://trac.macports.org/ticket/63297

A solution to fix the API breakage was proposed to MacPorts but we
should not attempt to declare ourselves the owners of this software. We
should not introduce yet another different version of this software that
is unlike what other distros ship. The fix should be proposed to the
developers of this software and they can decide (or not) what to do. In
anticipation of the developers not responding to such a proposal, like
they have already failed for one year to respond to the bug report about
the breakage, let us stay on the last unbroken version and backport any
needed bugfixes until such a time as the current developers begin
addressing bug reports or a better-maintained fork emerges.

Closes: #11781

Before, with mp4v2 @5.0.1_0:

cmus @2.9.1_0+aac:
checking for header <mp4v2/mp4v2.h>... no
checking for header <mp4.h>... no
configure failed.

ices0 @0.4_3:
In file included from in_mp4.c:32:
In file included from /opt/local/include/mp4v2/mp4v2.h:58:
/opt/local/include/mp4v2/file.h:336:34: error: use of undeclared identifier 'nullptr'

libextractor @1.4_3:
checking mp4v2/mp4v2.h usability... no
checking mp4v2/mp4v2.h presence... yes
configure: WARNING: mp4v2/mp4v2.h: present but cannot be compiled
configure: WARNING: mp4v2/mp4v2.h:     check for missing prerequisite headers?
configure: WARNING: mp4v2/mp4v2.h: see the Autoconf documentation
configure: WARNING: mp4v2/mp4v2.h:     section "Present But Cannot Be Compiled"
configure: WARNING: mp4v2/mp4v2.h: proceeding with the compiler's result
configure: WARNING:     ## --------------------------------------- ##
configure: WARNING:     ## Report this to bug-libextractor@gnu.org ##
configure: WARNING:     ## --------------------------------------- ##
checking for mp4v2/mp4v2.h... no

After, with mp4v2 @4.1.3_0:

cmus @2.9.1_0+aac:
checking for header <mp4v2/mp4v2.h>... yes
checking for header <neaacdec.h>... yes
checking for MP4_LIBS (-lmp4v2 -lfaad -lm)... yes

ices0 @0.4_4:
successful build

libextractor @1.4_3:
checking mp4v2/mp4v2.h usability... yes
checking mp4v2/mp4v2.h presence... yes
checking for mp4v2/mp4v2.h... yes